@ echo off
ECHO *********************************************************
ECHO COPIANDO ARQUIVOS DE INICIALIZAÇÃO ...
ECHO POR FAVOR, AGUARDE!
ECHO *********************************************************
COPY QTINTF.DLL TO C:\WINDOWS\system32
copy qtintf70.DLL TO C:\WINDOWS\system32
echo **********************************************************
echo ***** DIGITE EXIT PARA RETORNAR AO WINDOWS *****
echo **********************************************************






